@section('title')
<title>{{ucfirst($settings['site_name'])}} :::Privacy Policy</title>
<meta  name="description" content="Privacy Policy">
<meta itemprop="keywords" name="keywords" content="{{ucfirst($settings['site_name'])}} - Privacy Policy"/>
<meta name="author" content="{{ucfirst($settings['site_name'])}}" />

@endsection
@extends('layouts.app')
@section('content')


@section('sub')
 <div class="uk-width-1-1 in-breadcrumb">
                        <ul class="uk-breadcrumb uk-text-uppercase"><li><a href="{{url('/')}}">Home</a></li><li><a href="#"></a></li>
                          </ul>
                    </div>
@endsection
<main>
   <div class="uk-section uk-padding-large">
        <div class="uk-container in-wave-4">
            <div class="uk-grid uk-flex uk-flex-left">
             
                  <div class="uk-width-3-4@m">
                    <h1 class="uk-margin-remove-bottom">Privacy<span class="in-highlight">  Policy</span></h1>
                </div>
                <br>  <br>                <br>  <br>

               
            <p>We understand the importance of keeping your Personal Information private and confidential. For this very reason we are committed to protecting your Personal Information with due skill and our best knowledge.</p>
            <br>
            <h2>1. How we collect your Personal Information</h2>
            <br>
            <p>We collect your Personal Information when you:</p>
            <ul>
                <li>Sign up for an account with us;</li>
                <li>Order and use services from us;</li>
                <li>Make a purchase through our website;</li>
                <li>Submit a query or request to us;</li>
                <li>Subscribe for our updates and advertising materials;</li>
                <li>We may obtain Personal Information from publicly available sources, i.e. corporate and professional websites, regulatory filings, etc.;</li>
                <li>We may collect Personal Information from a third party, such as through your representatives and contractors or third parties who refer you to us as they think you might be interested in our services.</li>
            </ul>
            <br>
            <h2>2. Why we collect your Personal Information</h2>
            <br>
            <p>We process your data for the fulfilment of the following purposes:</p>
            <ul>
                <li>Creation of login credentials to access our website;</li>
                <li>Processing of payment transactions for services purchased;</li>
                <li>Verification of your identity;</li>
                <li>Determining your compliance with the terms and conditions that apply to any of our services and applicable laws;</li>
                <li>Providing government authorities with the information they may require us to disclose;</li>
                <li>Sending you promotional emails;</li>
                <li>Contacting you when it is needed (notifying you about our updates, technical issues, etc.)</li>
                <li>Researching markets;</li>
                <li>Complying with with our obligations.</li>
            </ul>
            <b>
            <h2>3. Legal Basis</h2>
            <br>
            <p>There’s a legal basis for collecting your Personal Information, as processing is required for the performance of our obligations to which you are party, for our operational and marketing purposes and other legitimate interests, but only to the extent our legitimate interests do not violate your fundamental rights and freedoms.</p>
            <br>
            <h2>4. How we share your Personal Information</h2>
            <br>
            <p>We do not share your Personal Information outside of the usage of our website and its relevant services.</p>
            <p>We may share your Personal Information if it is required to comply with the laws, or for the safety of Our Proposal and services.</p>
            <p>We may also share your Personal Information with our service providers (i.e. processing centers, organizations that maintain our networks, etc.). These third parties act as data processors and are strictly controlled in how they may or may not use your information and we remain responsible for protecting your Personal Information.</p>
            <br>
            <h2>5. How we use cookies</h2><br>
            <p>A Cookie is a small amount of data generated by our website and saved by your web browser. It enables our website to remember information about you and, as a result, to serve you effectively. For example, cookies enable our website to remember your login information so that you do not have to enter it every time you return to our website.</p>

            <p>Keep in mind that enabling cookies is not necessary for our website to work, it just provides you with better browsing experience.</p>

            <p>In no event shall we use information obtained from cookies to identify your personality.</p>

            <p>You can disable cookies at any time upon your own discretion. If you do not know how to disable cookies, please, refer to your browser’s help menu. For your convenience we gathered the links to instructions on how to turn off cookies for the popular browsers, please find below:</p>

            <p>Chrome <a class="dont-break-out" href="https://support.google.com/accounts/answer/61416?co=GENIE.Platform%3DDesktop&amp;hl=en">https://support.google.com/accounts/answer/61416?co=GENIE.Platform%3DDesktop&amp;hl=en</a></p>
            <p>Mozilla Firefox <a class="dont-break-out" href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</a></p>
            <br>
            <h2>How we store your personal Information</h2>
            <br>
            <p>We store Personal Information that we collect in electronic databases both our databases or third party’s data storages, which may be located outside of  as well. Although we use technical and physical safeguards to protect your Personal Information, we warn you the transmission of information via internet is not completely secure and any transmission is made at your own risk.</p>
            <br>
            <h2>Length of Data Retention</h2>
            <br>
            <p>We retain your Personal Information to meet our legal, operational, contractual and regulatory obligations. For each type of records the recordkeeping requirements may vary so we guarantee that in no event shall we retain your Personal Information longer than required. Please contact us at 
                <a href="">
                    {{$settings['site_email']}}</a></p>

            <p>if you would like to know more about length of retention for a specific data.</p>
            <br>
            <h2>How to control what we collect and how we use your Personal Information</h2>
            <br>
            <p>If you would like to access your Personal Information that we collected, update, amend or change your Personal Information, request to remove or restrict use of specific Personal Information, or other, please contact us at <a href="">
                    {{$settings['site_email']}}</a></p>
            <br>
            <h2>Right to Lodge a Complaint with a Supervisory Authority</h2>
            <br>
            <p>You have the right to lodge a complaint with a supervisory authority if you believe that processing of your Personal Information infringes this Privacy Policy, data protection principles or laws.</p>
            <br>
            <h2>Privacy Policy Changes</h2>
            <br>
            <p>We reserve the right to update this Privacy Policy from time to time. You can always find the latest version of this policy on our website.</p>

            <p>We make sure our employees, providers and agents uphold these obligations.</p>

            <p>By using our website you agree to this Privacy Policy.</p>
            <br>
            <h2>How to contact us</h2>
            <br>
            <p>Should you have any questions or require further information on privacy matters, please, feel free to contact us at 
                <a href="">{{$settings['site_email']}}</a></p>
            <br>
            <p>{{$settings['site_name']}}</p>
            <p>{{$settings['address']}}</p>

            </div>
        </div>
    </div>
</main>


@endsection